export WERCKER_BUILD_ID=522eeba48a8d9f4406004303
export WERCKER_APPLICATION_ID="510a2efc5ff9d06a77000574"
export WERCKER_RESULT=failed
export WERCKER_FAILED_STEP_DISPLAY_NAME="Run tests"
export WERCKER_FAILED_STEP_MESSAGE=""
export WERCKER_STARTED_BY="Peter de Ruijter"
export WERCKER_APPLICATION_NAME="one"
export WERCKER_APPLICATION_OWNER_NAME="wrdevos"
export WERCKER_GIT_COMMIT="9c72e232762ec230cc23798732ab1701b4143efa"
export WERCKER_GIT_BRANCH="master"
export WERCKER_STEP_ROOT="."

export WERCKER_FLOWDOCK_NOTIFY_FLOW_API_TOKEN="XXX"
export WERCKER_FLOWDOCK_NOTIFY_FROM_ADDRESS="test@test.com"
export WERCKER_FLOWDOCK_NOTIFY_PASSED_EXTRA_MESSAGE="<p>Foobar</p><ul><li>Uno due tre</li></ul>"
export WERCKER_FLOWDOCK_NOTIFY_FAILED_EXTRA_MESSAGE="<p>Foobar</p><ul><li>Uno due tre</li></ul>"

./run.sh

